name: totes-infrastructure-deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout and Clone Repo 
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create Environment with Requirements
        run: make requirements

      - name: Create Dev Setup 
        run: make dev-setup

      - name: Run All Checks
        if: github.event_name == 'pull'
        run: make run-checks

  deploy-terraform:
    name: deploy-terraform-code
    runs-on: ubuntu-latest 
    needs: run-tests 
    steps: 
      - name: Checkout and clone repo 
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: set up credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: terraform init
        working-directory: terraform
        run: terraform init

      - name: terraform format
        working-directory: terraform
        run: terraform fmt

      - name: terraform plan
        working-directory: terraform
        run: terraform plan

      - name: terraform apply
        if: github.event_name == 'push'
        working-directory: terraform
        run: |
          terraform apply \
          -replace=null_resource.prepare_layer_files \
          -replace=aws_s3_object.helper_layer_code \
          -replace=aws_lambda_layer_version.helper_lambda_layer \
          -replace=null_resource.prepare_layer_files_transform \
          -replace=aws_s3_object.transform_layer_code \
          -replace=aws_lambda_layer_version.transform_lambda_layer \
          -replace=null_resource.prepare_layer_files_load \
          -replace=aws_s3_object.load_layer_code \
          -replace=aws_lambda_layer_version.load_lambda_layer \
          -auto-approve