name: totes-infrastructure-deployment

on:
  pull_request:
    branches:
      - main


jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout and Clone Repo 
        uses: actions/checkout@v4
      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Create Environment with Requirements
        run: make requirements
      - name: Create Dev Setup 
        run: make dev-setup
      - name: Run All Checks
        run: make run-checks

  deploy-terraform:
    name: deploy-terraform-code
    runs-on: ubuntu-latest 
  # To be un-commented when source code and tests have been written 
    needs: run-tests 
    steps: 
      - name: Checkout and clone repo 
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      # AWS credentials
      - name: set up credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Terraform steps
      - name: terraform init
        working-directory: terraform
        run: terraform init
      - name: terraform format
        working-directory: terraform
        run: terraform fmt
      - name: terraform plan
        working-directory: terraform
        run: terraform plan
      - name: terraform apply 
        working-directory: terraform
        run: terraform apply -replace=aws_lambda_layer_version.helper_lambda_layer -auto-approve

